### ISSUE TITLE
Please change static public => public static

### ISSUE THREAD

**Issue by magicsunday** [XenosEleatikos/MusicBrainz#1]
From PSR-2:

Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility. [reference]

**Comment by XenosEleatikos** [comment]
Fixed by [54269abbb96b9d36649b47c8e17bc2bfc6dfaf70](https://github.com/XenosEleatikos/MusicBrainz/commit/54269abbb96b9d36649b47c8e17bc2bfc6dfaf70)
