### ISSUE TITLE
Undefined array key "release"

### ISSUE THREAD

**Issue by roland-d** [XenosEleatikos/MusicBrainz#10]
Hello @XenosEleatikos 

I am getting the following notice when I call this URL: 
> PHP Warning:  Undefined array key "release" in vendor/xenos/musicbrainz/src/Helper/RelationFactory.php on line 48

This can be reproduce by calling this URL:
https://musicbrainz.org/ws/2/artist/82eb8936-7bf6-4577-8320-a2639465206d?fmt=json&inc=recordings%2Bartist-rels%2Bevent-rels%2Binstrument-rels%2Blabel-rels%2Bplace-rels%2Brecording-rels%2Brelease-group-rels%2Brelease-rels%2Bseries-rels%2Bwork-rels

From what I have found is that the array key `release`  is never returned by MusicBrainz and as such generates the warning. In the `RelationFactory.php` there is already a todo :) I just wonder if we should be looking for the word `release` because it is not returned by MusicBrainz.

```php
if (is_null($relation[(string) $relatedEntityType])) {
            /** @todo Implement fallback for undefined relation */
            die;
        }
```

Testing file:
```php
<?php

require "vendor/autoload.php";

use MusicBrainz\Filter\PageFilter;
use MusicBrainz\Filter\Search\ArtistFilter;
use MusicBrainz\MusicBrainz;
use MusicBrainz\HttpAdapter\GuzzleHttpAdapter;
use GuzzleHttp\Client;
use MusicBrainz\Supplement\Lookup\ArtistFields;
use MusicBrainz\Value\Artist;
use MusicBrainz\Value\MBID;
use MusicBrainz\Value\Name;

$guzzleHttpAdapter = new GuzzleHttpAdapter(new Client);
$musicBrainz       = new MusicBrainz($guzzleHttpAdapter);
$artistFilter = new ArtistFilter;
$artistFilter->addArtistNameWithAccents(new Name('Jason Mraz'));
$pageFilter = new PageFilter(0, 1);

$artistList = $musicBrainz->api()->search()->artist($artistFilter, $pageFilter);

/** @var Artist $current */
$current = $artistList->current()->getArtist();

$fields = (new ArtistFields)
    ->includeAreaRelations()
    ->includeArtistRelations()
    ->includeEventRelations()
    ->includeInstrumentRelations()
    ->includeLabelRelations()
    ->includePlaceRelations()
    ->includeRecordingRelations()
    ->includeReleaseRelations()
    ->includeRecordings()
    ->includeReleaseGroupRelations()
    ->includeSeriesRelations()
    ->includeWorkRelations();

try {
    $artist = $musicBrainz->api()->lookup()->artist(
        new MBID($current->getMBID()),
        $fields
    );
}
catch (Exception $exception) {
    echo $exception->getMessage();
}

foreach ($artist->getRelations()->getAreaRelations() as $relation) {
    print_r($relation);
    print_r($relation->getArea());
}

foreach ($artist->getRelations()->getArtistRelations() as $relation) {
    print_r($relation->getArtist());
}

foreach ($artist->getRelations()->getEventRelations() as $relation) {
    print_r($relation->getEvent());
}

foreach ($artist->getRelations()->getInstrumentRelations() as $relation) {
    print_r($relation->getInstrument());
}

foreach ($artist->getRelations()->getLabelRelations() as $relation) {
    print_r($relation->getLabel());
}

foreach ($artist->getRelations()->getPlaceRelations() as $relation) {
    print_r($relation->getPlace());
}

foreach ($artist->getRelations()->getRecordingRelations() as $relation) {
    print_r($relation->getRecording());
}

foreach ($artist->getRelations()->getReleaseRelations() as $relation) {
    print_r($relation->getRelease());
}

foreach ($artist->getRelations()->getReleaseGroupRelations() as $relation) {
    print_r($relation->getReleaseGroup());
}

foreach ($artist->getRelations()->getSeriesRelations() as $relation) {
    print_r($relation->getSeries());
}

foreach ($artist->getRelations()->getWorkRelations() as $relation) {
    print_r($relation->getWork());
}
```

**Comment by XenosEleatikos** [comment]
Solved by https://github.com/XenosEleatikos/MusicBrainz/pull/8

**Comment by XenosEleatikos** [comment]
Thanks for this bug report. Unfortunately I cannot look at this issue for the next 10 days. But I will do later.

**Comment by XenosEleatikos** [comment]
... Have you tested it this with the newest master? Maybe this warning does not appear any more, because some lines above a message is logged now and the method returns null, if the relationship is not implemened. If the warning still appears, you can also return null there and log a more speaking method instead of the die-statement. That would just lead to a missing relationship instead of a broken request. (Writing this from the smartphone, so cannot test for myself.)

**Comment by roland-d** [comment]
@XenosEleatikos I was being a little stupid, I pulled master but did not realize it was my fork and not upstream :) So after pulling the correct master and change `die; ` to `return null;`. The request works fine except for the missing relationship of course.

**Comment by roland-d** [comment]
Hello @XenosEleatikos I am at this again :)

So I have run into this again but now with another entry, this one:
https://musicbrainz.org/ws/2/recording/91362252-e1d6-4ab1-afb1-b692786768e7?inc=artist-rels+recording-rels+series-rels+url-rels&fmt=json

This URL fails on this relation:
![image](https://github.com/XenosEleatikos/MusicBrainz/assets/359377/4935d3f6-c74e-4fb7-be31-4aef0d275045)

The `type-id` is that of `MusicBrainz\Relation\Type\Recording\Recording\CoversAndVersions\Edit` which returns a `release` type. As you can see in the array, there is no release but there is a recording just as the `target-type` specifies. This makes me wonder if we should look at the `target-type` instead of the `type-id`. 

I have created a PR to check: #15

**Comment by XenosEleatikos** [comment]
Hi @roland-d ,

first of all, sorry for late response. Now I found some time to have a look at this issue.
I fixed the bug here: https://github.com/XenosEleatikos/MusicBrainz/commit/de31949e042df0882e34b77ff07a67247b33c193
End I fixed the error handling here: https://github.com/XenosEleatikos/MusicBrainz/commit/dce018bb62f6594d17c4ca73470e498b8cfc32bd

Maybe you're right, and we can look simply in `$relation['target-type']` instead of looking in our own definitions. I will have a closer look at it later and since I don't have more insights I don't want to risk this change.

Thanks agian for your reporting.

Best
Christoph

**Comment by XenosEleatikos** [comment]
Hi @roland-d , could you please have a look at my latest commit https://github.com/XenosEleatikos/MusicBrainz/commit/8f6866100788ae00b393e61ec5be90892f31ab6c

I wrote a web crawler for the documentation https://musicbrainz.org/relationships and a code generator writing all the missing PHP classes.

If it's okay for you I would close this issue. And please let me know if you have any ideas for the relationships or the library in general.

Best
Christoph
