### ISSUE TITLE
Detected error in TrackDisplayNumberTrait.php

### ISSUE THREAD

**Issue by papposilene** [XenosEleatikos/MusicBrainz#3]
Hi everyone, 

The file `Value/Property/TrackDisplayNumber.php` contains an error in its `setTrackDisplayNumberFromArray` function. It's using `$this->length` instead of something like `$this->trackDisplayNumber`. 

:-)

**Comment by XenosEleatikos** [comment]
So sorry dude ;) Weekend tested!

**Comment by XenosEleatikos** [comment]
Solved by 67eb9d2cd6a942851fbfe21d0e6ce7185fbe8ba9

Thanks for that!
