### ISSUE TITLE
How to get the URL from  an EntityType Object?

### ISSUE THREAD

**Issue by roland-d** [XenosEleatikos/MusicBrainz#7]
Hello,

Currently I am testing this library with MusicBrainz and generally it works really well. Now I am running into an issue which I am not sure is a bug or me not understanding how it works :)

I am doing an artist lookup using an MBID and I have set the `includeURLRelations`. That all works good and I can see the URLs when I dump the result.

What I fail to see how to do, how I get the URL value from the object? The `$url` in the `RealtionToUrl` class is private and I do not see a get method for it. Should I be able to get the URL or should I handle that differently?

Thank you.

**Comment by XenosEleatikos** [comment]
Hi Roland,

you're right. Getters are simply missing. Could you please check my pull request?

https://github.com/XenosEleatikos/MusicBrainz/pull/8/files

Best
Christoph

**Comment by roland-d** [comment]
Hello @XenosEleatikos 

Thank you for merging my PR and your quick responses. I will test your PR on Tuesday when I am back in the office.

**Comment by XenosEleatikos** [comment]
Solved by https://github.com/XenosEleatikos/MusicBrainz/pull/8
